
services:
  mysql:
    image: mysql:8.3.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  meilisearch:
    image: getmeili/meilisearch:v1.13
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=Per4CS-nqIOaleb0fWQG_wrGqo5bqLiEHKffZFW_KtQ
    ports:
      - "7700:7700"
    volumes:
      - ./data/meili_data:/meili_data